version: "3"
services:
  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
      - "MYSQL_DATABASE=TRAPEZITE"
    volumes:
      - ./config/mysql:/etc/mysql/conf.d